### ISSUE TITLE
[fluent bit v.1.9] download section still lists v.1.8.11 (Windows)

### ISSUE THREAD

**Issue by hisa-tanaka** [fluent/fluentbit-website-v3#30]
The download links still show v.1.8.11. Need to be updated to ones for v.1.9.0.
https://docs.fluentbit.io/manual/installation/windows#installation-packages

![image](https://user-images.githubusercontent.com/19581009/158641936-62428c1d-2258-4ec7-9d9c-6a4059a01d95.png)

**Comment by patrick-stephens** [comment]
Resolved now but I cannot close this one unfortunately.

**Comment by hisa-tanaka** [comment]
Thank you! I've confirmed the update!
